const $=s=>document.querySelector(s), uid=()=>crypto.randomUUID(), colors=['#ff6b6b','#ffd93d','#6bcb77','#4d96ff','#a78bfa','#f472b6','#2dd4bf','#f59e0b'];
let state=JSON.parse(localStorage.getItem('roue-des-eleves')||'{"classes":[],"students":[],"history":[]}'), selectedClass=null, selectedStudent=null, winners=[];
const save=()=>localStorage.setItem('roue-des-eleves',JSON.stringify(state));
function note(text){$('#messageText').textContent=text;$('#message').showModal()}
function name(s){return `${s.first} ${s.last}`}
function render(){
  const cls=[...state.classes].sort((a,b)=>a.name.localeCompare(b.name)); if(selectedClass&&!cls.some(c=>c.id===selectedClass))selectedClass=cls[0]?.id||null;
  $('#classList').innerHTML=cls.map(c=>`<li data-id="${c.id}" class="${c.id===selectedClass?'selected':''}">${c.name}</li>`).join('')||'<li class="hint">Aucune classe.</li>';
  const students=state.students.filter(s=>s.classId===selectedClass).sort((a,b)=>name(a).localeCompare(name(b)));
  $('#studentsTitle').textContent=selectedClass?`Élèves de ${cls.find(c=>c.id===selectedClass).name}`:'Élèves de la classe';
  $('#studentList').innerHTML=students.map(s=>`<li data-id="${s.id}" class="${s.id===selectedStudent?'selected':''}">${name(s)}</li>`).join('')||'<li class="hint">Aucun élève.</li>';
  $('#drawClasses').innerHTML=cls.map(c=>`<label><input type="checkbox" value="${c.id}" ${drawIds().includes(c.id)?'checked':''}> ${c.name}</label>`).join('')||'<span class="hint">Créez une classe pour commencer.</span>';
  const selected=new Set(drawIds()), entries=state.history.filter(h=>selected.has(h.classId)).sort((a,b)=>b.at.localeCompare(a.at));
  $('#history').innerHTML=entries.map(h=>`<li>${h.studentName} — ${new Date(h.at).toLocaleString('fr-FR')}</li>`).join('')||'<li class="hint">Aucun tirage.</li>';
  $('#results').innerHTML=winners.map(w=>`<li class="selected">${w}</li>`).join('')||'<li class="hint">Les résultats apparaîtront ici.</li>';
  drawWheel(candidates());
}
function drawIds(){return [...document.querySelectorAll('#drawClasses input:checked')].map(e=>e.value)}
function candidates(){const ids=new Set(drawIds()), excluded=$('#excludeHistory')?.checked?new Set(state.history.filter(h=>ids.has(h.classId)).map(h=>h.studentName)):new Set();return state.students.filter(s=>ids.has(s.classId)&&!excluded.has(name(s)))}
function drawWheel(items){const c=$('#wheel'),ctx=c.getContext('2d'),size=c.width,mid=size/2,r=mid-38;ctx.clearRect(0,0,size,size);const names=items.map(name);$('#wheelMessage').textContent=names.length?`${names.length} élève${names.length>1?'s':''} disponible${names.length>1?'s':''}.`:'Sélectionnez au moins une classe.';if(!names.length){ctx.fillStyle='#edf2f7';ctx.beginPath();ctx.arc(mid,mid,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#64748b';ctx.font='28px Segoe UI';ctx.textAlign='center';ctx.fillText('Aucun élève',mid,mid+10);return} const arc=Math.PI*2/names.length;names.forEach((n,i)=>{let a=-Math.PI/2+i*arc;ctx.beginPath();ctx.moveTo(mid,mid);ctx.arc(mid,mid,r,a,a+arc);ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();ctx.save();ctx.translate(mid,mid);ctx.rotate(a+arc/2);ctx.fillStyle='#172033';ctx.font=`${Math.max(13,Math.min(23,400/names.length))}px Segoe UI`;ctx.textAlign='right';ctx.fillText(n.length>17?n.slice(0,16)+'…':n,r-20,6);ctx.restore()});ctx.beginPath();ctx.arc(mid,mid,57,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#27334a';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#27334a';ctx.font='bold 19px Segoe UI';ctx.textAlign='center';ctx.fillText(winners[0]||'Tirage',mid,mid+7);ctx.fillStyle='#ef4444';ctx.beginPath();ctx.moveTo(mid-14,13);ctx.lineTo(mid+14,13);ctx.lineTo(mid,48);ctx.fill()}
function addClass(e){e.preventDefault();const n=$('#className').value.trim();if(!n)return;if(state.classes.some(c=>c.name.toLowerCase()===n.toLowerCase()))return note('Cette classe existe déjà.');const c={id:uid(),name:n};state.classes.push(c);selectedClass=c.id;$('#className').value='';save();render()}
function addStudent(e){e.preventDefault();if(!selectedClass)return note('Sélectionnez d’abord une classe.');const first=$('#firstName').value.trim(),last=$('#lastName').value.trim();if(!first||!last)return; if(state.students.some(s=>s.classId===selectedClass&&s.first.toLowerCase()===first.toLowerCase()&&s.last.toLowerCase()===last.toLowerCase()))return note('Cet élève est déjà présent.');state.students.push({id:uid(),classId:selectedClass,first,last});$('#studentForm').reset();save();render()}
function normal(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ')}
function split(full){let p=String(full).trim().split(/\s+/);if(p.length<2)return [p[0]||'', ''];let upper=p.findIndex(x=>x===x.toUpperCase());if(upper===0)return [p.slice(1).join(' '),p[0]];if(p.at(-1)===p.at(-1).toUpperCase())return [p.slice(0,-1).join(' '),p.at(-1)];return [p[0],p.slice(1).join(' ')]}
async function importExcel(e){const f=e.target.files[0];e.target.value='';if(!f)return;if(!window.XLSX)return note('L’outil d’import Excel nécessite une connexion Internet au premier chargement.');try{const data=await f.arrayBuffer(),rows=XLSX.utils.sheet_to_json(XLSX.read(data,{type:'array'}).Sheets[XLSX.read(data,{type:'array'}).SheetNames[0]],{header:1,defval:''});let header=rows.findIndex(r=>r.filter(x=>['nom','classe','sexe','age','regime','date de naissance'].includes(normal(x))).length>=3);if(header<0)throw Error('Aucune ligne d’en-tête valide n’a été trouvée.');const heads=rows[header].map(normal),ni=heads.findIndex(x=>['nom','nom complet','nom prenom','nom et prenom'].includes(x)),ci=heads.findIndex(x=>['classe','niveau','promotion'].includes(x));if(ni<0||ci<0)throw Error('Les colonnes Nom et Classe sont obligatoires.');let count=0;for(const row of rows.slice(header+1)){const full=row[ni],className=String(row[ci]||'').trim();if(!String(full).trim()||!className)continue;let cl=state.classes.find(c=>c.name.toLowerCase()===className.toLowerCase());if(!cl){cl={id:uid(),name:className};state.classes.push(cl)}let[first,last]=split(full);if(first&&last&&!state.students.some(s=>s.classId===cl.id&&s.first.toLowerCase()===first.toLowerCase()&&s.last.toLowerCase()===last.toLowerCase())){state.students.push({id:uid(),classId:cl.id,first,last});count++}}save();render();note(`${count} élève(s) importé(s).`)}catch(err){note(`Import impossible : ${err.message}`)}}
function launch(){const people=candidates(),n=Number($('#drawCount').value)||1;if(!drawIds().length)return note('Sélectionnez au moins une classe.');if(people.length<n)return note(`Il n’y a que ${people.length} élève(s) disponible(s).`);$('#drawButton').disabled=true;let ticks=0,timer=setInterval(()=>{winners=[name(people[Math.floor(Math.random()*people.length)])];drawWheel(people);if(++ticks===18){clearInterval(timer);const pool=[...people];winners=[];while(winners.length<n){winners.push(name(pool.splice(Math.floor(Math.random()*pool.length),1)[0]))}const ids=new Set(drawIds());for(const w of winners){const s=state.students.find(x=>name(x)===w&&ids.has(x.classId));state.history.push({id:uid(),classId:s.classId,studentName:w,at:new Date().toISOString()})}save();$('#drawButton').disabled=false;render()}},90)}
document.addEventListener('click',e=>{const li=e.target.closest('#classList li[data-id]');if(li){selectedClass=li.dataset.id;selectedStudent=null;render()}const st=e.target.closest('#studentList li[data-id]');if(st){selectedStudent=st.dataset.id;render()}});
$('#classForm').onsubmit=addClass;$('#studentForm').onsubmit=addStudent;$('#excelFile').onchange=importExcel;$('#deleteClass').onclick=()=>{if(!selectedClass)return note('Sélectionnez une classe.');if(confirm('Supprimer cette classe et ses élèves ?')){state.students=state.students.filter(s=>s.classId!==selectedClass);state.history=state.history.filter(h=>h.classId!==selectedClass);state.classes=state.classes.filter(c=>c.id!==selectedClass);save();render()}};$('#deleteStudent').onclick=()=>{if(!selectedStudent)return note('Sélectionnez un élève.');state.students=state.students.filter(s=>s.id!==selectedStudent);selectedStudent=null;save();render()};$('#drawClasses').onchange=render;$('#excludeHistory').onchange=render;$('#drawButton').onclick=launch;$('#resetButton').onclick=()=>{winners=[];render()};$('#clearHistory').onclick=()=>{const ids=new Set(drawIds());if(ids.size&&confirm('Vider l’historique des classes sélectionnées ?')){state.history=state.history.filter(h=>!ids.has(h.classId));save();render()}};$('#closeMessage').onclick=()=>$('#message').close();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.tab}`).classList.add('active');render()});let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{installPrompt?.prompt();await installPrompt?.userChoice;$('#installButton').hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');render();
